name: CI-CD

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Build & Push Action
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./kube-news/
          file: ./kube-news/Dockerfile
          push: true
          tags: |
            rogeriop1990cv/kubenews:latest
            rogeriop1990cv/kubenews:${{ github.run_number }}
  CD: 
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.2
        with:
          images: rogeriop1990cv/kubenews:${{ github.run_number }}
          manifests: |
            /kube-news/k8s/deployment.yaml
            
